---
skylounge-yml: "7fb6ae28ebb8e3a513f571569d626b621a9fb123"
skylounge-yml-html-url: "https://github.com/sky-lounge/demo-application/blob/d29f03ee4906ca40ea72e603530a0f103d77f953/skylounge.yml"
lifecycle-template:
  id: "blueprint"
  template-uri: "sky-lounge/skylounge-definitions/lifecycle-templates/cloud-run/lifecycle-template.yml"
  sha: "b88c0a85f7a8fdde69ff872447ea2f25f14871cd"
  html-url: "https://github.com/sky-lounge/skylounge-definitions/blob/b436dfce60801dd75d3604576ff35ef16a96318f/lifecycle-templates/cloud-run/lifecycle-template.yml"
workflows:
- id: "develop-branch"
  template-uri: "sky-lounge/skylounge-definitions/lifecycle-templates/cloud-run/develop-branch.yml"
  sha: "f877c7e0c8a193920c86784a6b304a89f75d7864"
  html-url: "https://github.com/sky-lounge/skylounge-definitions/blob/b436dfce60801dd75d3604576ff35ef16a96318f/lifecycle-templates/cloud-run/develop-branch.yml"
  jobs:
  - id: "integration-test"
    template-uri: "sky-lounge/demo-application/skylounge/jobs/integration-test.yml"
    sha: "cdb5d562ddf6cffaf2d224f76b21befe9fc5c3a5"
    html-url: "https://github.com/sky-lounge/demo-application/blob/d29f03ee4906ca40ea72e603530a0f103d77f953/skylounge/jobs/integration-test.yml"
  steps:
  - id: "build-container-image"
    template-uri: "sky-lounge/skylounge-definitions/step-templates/pack/nginx/build-steps.yml"
    sha: "4172dc4b981c2fcaaa41bde233a291bad9d350fe"
    html-url: "https://github.com/sky-lounge/skylounge-definitions/blob/b436dfce60801dd75d3604576ff35ef16a96318f/step-templates/pack/nginx/build-steps.yml"
