---
skylounge-yml: "407e8ce90bd0e533a0b6fb5b17e6f7c1b5db7e91"
skylounge-yml-html-url: "https://github.com/sky-lounge/hello/blob/56dd54c6787cf3e1fd60da1e81f1efda5c5c0b81/skylounge.yml"
lifecycle-template:
  id: "blueprint"
  template-uri: "sky-lounge/skylounge-definitions/blueprints/hello-world/blueprint.yml"
  sha: "f34e8ea991b9c187bdaecdcedff9171f34689d92"
  html-url: "https://github.com/sky-lounge/skylounge-definitions/blob/cfe57e793ddc5f37687a77aecbe90dd73be64e53/blueprints/hello-world/blueprint.yml"
workflows:
- id: "build-deploy"
  template-uri: "sky-lounge/skylounge-definitions/blueprints/hello-world/build-deploy.yml"
  sha: "79db0e2c280729f7ad49d2d58c2f7ccd5bec5d8e"
  html-url: "https://github.com/sky-lounge/skylounge-definitions/blob/cfe57e793ddc5f37687a77aecbe90dd73be64e53/blueprints/hello-world/build-deploy.yml"
  jobs:
  - id: "integration-test"
    template-uri: "sky-lounge/hello/skylounge/jobs/integration-test.yml"
    sha: "ca1968ed4a12ea16adbe79468a43ec824ecebebe"
    html-url: "https://github.com/sky-lounge/hello/blob/56dd54c6787cf3e1fd60da1e81f1efda5c5c0b81/skylounge/jobs/integration-test.yml"
  steps:
  - id: "build-container-image"
    template-uri: "sky-lounge/skylounge-definitions/step-templates/docker/build-steps.yml"
    sha: "ed2621386b603fa0e6e247887ff112931b581c55"
    html-url: "https://github.com/sky-lounge/skylounge-definitions/blob/cfe57e793ddc5f37687a77aecbe90dd73be64e53/step-templates/docker/build-steps.yml"
