---
skylounge-yml: "e03090c1152aff01bbeb0d3311ab6c511ab253b1"
skylounge-yml-html-url: "https://github.com/sky-lounge/hello/blob/9955a714f9f7702d34e69deb2b0f0e9a1dc2e41d/skylounge.yml"
lifecycle-template:
  id: "blueprint"
  template-uri: "sky-lounge/skylounge-definitions/blueprints/hello-world/blueprint.yml"
  sha: "713550353389e6c3bcd589a80c0f993ce3e76c0b"
  html-url: "https://github.com/sky-lounge/skylounge-definitions/blob/9ed4b22f9a222a9c40de44384c8cccf5393241fc/blueprints/hello-world/blueprint.yml"
workflows:
- id: "build-deploy"
  template-uri: "sky-lounge/skylounge-definitions/blueprints/hello-world/build-deploy.yml"
  sha: "5521f323e8cd467d86889e88a6058030e425c309"
  html-url: "https://github.com/sky-lounge/skylounge-definitions/blob/9ed4b22f9a222a9c40de44384c8cccf5393241fc/blueprints/hello-world/build-deploy.yml"
  jobs: []
  steps:
  - id: "build-container-image"
    template-uri: "sky-lounge/skylounge-definitions/step-templates/docker/build-steps.yml"
    sha: "e49e03b5c2d33c1bdc08df6e0933364aa03ca8da"
    html-url: "https://github.com/sky-lounge/skylounge-definitions/blob/9ed4b22f9a222a9c40de44384c8cccf5393241fc/step-templates/docker/build-steps.yml"
