---
skylounge-yml: "7fb6ae28ebb8e3a513f571569d626b621a9fb123"
skylounge-yml-html-url: "https://github.com/sky-lounge/demo-application/blob/9d5ed3542ef486eae37b7b468046d3b39b7ffbb2/skylounge.yml"
lifecycle-template:
  id: "blueprint"
  template-uri: "sky-lounge/skylounge-definitions/lifecycle-templates/cloud-run/lifecycle-template.yml"
  sha: "b88c0a85f7a8fdde69ff872447ea2f25f14871cd"
  html-url: "https://github.com/sky-lounge/skylounge-definitions/blob/f634fac74b5034ad19726796312e620c51d05a11/lifecycle-templates/cloud-run/lifecycle-template.yml"
workflows:
- id: "develop-branch"
  template-uri: "sky-lounge/skylounge-definitions/lifecycle-templates/cloud-run/develop-branch.yml"
  sha: "385cf63f8e77c68c8f4e74a8968fa56b484f5f48"
  html-url: "https://github.com/sky-lounge/skylounge-definitions/blob/f634fac74b5034ad19726796312e620c51d05a11/lifecycle-templates/cloud-run/develop-branch.yml"
  jobs:
  - id: "integration-test"
    template-uri: "sky-lounge/demo-application/skylounge/jobs/integration-test.yml"
    sha: "cdb5d562ddf6cffaf2d224f76b21befe9fc5c3a5"
    html-url: "https://github.com/sky-lounge/demo-application/blob/9d5ed3542ef486eae37b7b468046d3b39b7ffbb2/skylounge/jobs/integration-test.yml"
  steps:
  - id: "build-container-image"
    template-uri: "sky-lounge/skylounge-definitions/step-templates/pack/nginx/build-steps.yml"
    sha: "4172dc4b981c2fcaaa41bde233a291bad9d350fe"
    html-url: "https://github.com/sky-lounge/skylounge-definitions/blob/f634fac74b5034ad19726796312e620c51d05a11/step-templates/pack/nginx/build-steps.yml"
