---
skylounge-yml: "7fb6ae28ebb8e3a513f571569d626b621a9fb123"
skylounge-yml-html-url: "https://github.com/sky-lounge/demo-application/blob/2b54f2cfdac41962f041996eca4c0cd419b7fa88/skylounge.yml"
lifecycle-template:
  id: "blueprint"
  template-uri: "sky-lounge/skylounge-definitions/lifecycle-templates/cloud-run/lifecycle-template.yml"
  sha: "8c8130aeb919d4bc64aa31187175da25e82d8dc9"
  html-url: "https://github.com/sky-lounge/skylounge-definitions/blob/b48536878bd7202d763e75c4b3c771a4aad27d47/lifecycle-templates/cloud-run/lifecycle-template.yml"
workflows:
- id: "develop-branch"
  template-uri: "sky-lounge/skylounge-definitions/lifecycle-templates/cloud-run/develop-branch.yml"
  sha: "f877c7e0c8a193920c86784a6b304a89f75d7864"
  html-url: "https://github.com/sky-lounge/skylounge-definitions/blob/b48536878bd7202d763e75c4b3c771a4aad27d47/lifecycle-templates/cloud-run/develop-branch.yml"
  jobs:
  - id: "integration-test"
    template-uri: "sky-lounge/demo-application/skylounge/jobs/integration-test.yml"
    sha: "cdb5d562ddf6cffaf2d224f76b21befe9fc5c3a5"
    html-url: "https://github.com/sky-lounge/demo-application/blob/2b54f2cfdac41962f041996eca4c0cd419b7fa88/skylounge/jobs/integration-test.yml"
  steps:
  - id: "build-container-image"
    template-uri: "sky-lounge/skylounge-definitions/step-templates/pack/nginx/build-steps.yml"
    sha: "4172dc4b981c2fcaaa41bde233a291bad9d350fe"
    html-url: "https://github.com/sky-lounge/skylounge-definitions/blob/b48536878bd7202d763e75c4b3c771a4aad27d47/step-templates/pack/nginx/build-steps.yml"
