apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE_NAME}-${ENVIRONMENT}
spec:
  template:
    spec:
      timeoutSeconds: 300
      containers:
        - image: ${IMAGE_NAME}
          resources:
            limits:
              cpu: "1"
