---
name: Build-Deploy
on:
  push:
    branches:
    - main
    paths:
    - public/**
jobs:
  build:
    name: Build container image
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    env:
      REGISTRY: us-west1-docker.pkg.dev/sky-lounge-director/skylounge-images
      REGISTRY_BASE_URL: us-west1-docker.pkg.dev
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    - name: Set image name
      run: |
        echo "IMAGE_NAME=${{ env.REGISTRY }}/${{ github.event.repository.name }}:${{ github.sha }}" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v3
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: "${{ env.IMAGE_NAME }}"
    - name: Push container image
      run: |
        gcloud auth configure-docker $REGISTRY_BASE_URL
        docker push ${{ env.IMAGE_NAME }}
